site_name: Guidepost

repo_name: 'HNU-CSEE-Nuwa/Guidepost'
repo_url: 'https://github.com/HNU-CSEE-Nuwa/Guidepost'
edit_uri: edit/main/docs/

nav:
  - 简介:
    - 简介: intro/intro.md
    - 贡献方法: intro/how-to-commit.md
    # - 收录内容:
  - 课程:
    - 公共课程:
      - 简介: lecture/general/intro.md
      - 高等数学A: lecture/general/advanced-math.md
      - 线性代数A: lecture/general/linear-algebra.md
      - 普通物理A: lecture/general/physics.md
      - 普通物理实验A: lecture/general/physics-experiment.md
      - 大学英语: lecture/general/english.md
      - 高等程序设计: lecture/general/advanced-programming.md
      - 算法分析与设计: lecture/general/algorithm.md
      - 数据结构: lecture/general/data-structure.md
      - 数字电路与逻辑设计: lecture/general/digital-circuits.md
      - 离散数学: lecture/general/discrete-mathematic.md
      - 数字系统实验: lecture/general/digital-system-experiment.md
      - 程序设计实验: lecture/general/programming-experiment.md
      - 一年级夏季学期: lecture/general/freshman-summer.md
      - 二年级夏季学期: lecture/general/sophomore-summer.md
    - 选修课: lecture/cs/cs.md
    - 计算机科学: 
      - 计算机系统: lecture/cs/computer-system.md
      - 人工智能导论: lecture/cs/ai.md
      - 操作系统: lecture/cs/os.md
      - 计算机网络: lecture/cs/network.md
      - 编译原理: lecture/cs/compiler.md
      - 数据库原理: lecture/cs/db.md
      - 软件工程: lecture/cs/software-engineering.md
      - 计算理论导论: lecture/cs/computing-theory.md
      - 高性能计算导论: lecture/cs/high-performance-computing.md
      - 计算方法: lecture/cs/computing-methods.md
      - 计算理论: lecture/cs/computing-theory-op.md
      - 云计算技术: lecture/cs/cloud-computing-technology.md
      - 社交网络分析: lecture/cs/social-network-analysis.md
      - 机器学习: lecture/cs/ml.md
      - 数据智能处理: lecture/cs/intelligent-processing-of-data.md
      - 科学计算可视化: lecture/cs/scientific-computing-visualization.md
      - 数据挖掘: lecture/cs/data-mining.md
      - 路由与交换技术: lecture/cs/routing-and-switching-technology.md
      - 分布式与云计算系统: lecture/cs/distributed-and-cloud-computing-system.md
      - 计算机视觉系统: lecture/cs/computer-vision-system.md
      - 软件设计模式: lecture/cs/software-design-patterns.md
      - 高级数据库设计: lecture/cs/advanced-database-designing.md
      - 三年级夏季学期: lecture/cs/junior-summer.md
    - 物联网工程: lecture/cs/cs.md
    - 智能科学与技术: lecture/cs/cs.md
    - 信息安全 / 保密管理: 
      - 算法设计与分析: lecture/is/algorithm.md
      - 计算机网络: lecture/is/computer-network.md
      - 数据库系统: lecture/is/database-system.md
      - 安全系统实验: lecture/is/security-system-experiment.md
      - 信息安全数学基础: lecture/is/information-security-mathematics-foundation.md
      - 保密技术基础A: lecture/is/secrecy-technology-foundation-A.md
      - 密码学: lecture/is/cryptography.md
      - 网络安全: lecture/is/network-security.md
      - 信息系统安全: lecture/is/information-system-security.md
      - 信息隐藏: lecture/is/information-hiding.md
      - 软件安全: lecture/is/software-security.md
      - 信息安全工程: lecture/is/information-security-engineering.md
      - 可信计算系统: lecture/is/trusted-computing-system.md
      - 信息内容安全: lecture/is/information-content-security.md
      - 涉密信息管理系统: lecture/is/the-classified-information-system-management.md
      - 保密技术基础B: lecture/is/secrecy-technology-foundation-B.md
      - 保密管理概论: lecture/is/introduction-to-secrecy-management.md
      - 保密法: lecture/is/secrecy-law.md
      - 保密史与保密制度: lecture/is/secrecy-history-and-secrecy-system.md
      - 机器学习: lecture/is/machine-learning.md
      - 数据挖掘: lecture/is/data-mining.md
      - 生物信息学: lecture/is/biological-information-science.md
    - 通信工程: lecture/cs/cs.md
    - 软件工程: lecture/cs/cs.md
    - 数字媒体技术: lecture/cs/cs.md
  - 升学:
    - 推研:
      - 介绍: postgraduate/recommendation/recommendation.md
      - 清华计科: postgraduate/recommendation/thu-cs.md
      - 北大信科: postgraduate/recommendation/pku-eecs.md
      - 北大软微: postgraduate/recommendation/pku-ss.md
      - 联系方式: postgraduate/recommendation/contact.md
    - 考研: postgraduate/exam/exam.md
    - 出国: postgraduate/abroad/abroad.md
  - 工作:
    - 介绍: job/job.md
  - 比赛: 
    - 介绍: competition/competition.md
    - Apple WWDC Student Scholarship: competition/wwdc.md
  - Tips: 
    - 介绍: tips/tips.md
    - MacOS 解决方案: tips/macos.md

theme:
  name: 'material'
  language: 'zh'
  custom_dir: overrides
  disqus: 'OI-Wiki'
  palette:
    primary: 'black'
    accent: 'red'
  icon:
    logo: 'material/school'
  features:
      - navigation.tabs
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

plugins:
  - git-revision-date
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
